ALTER TABLE companies ADD COLUMN IF NOT EXISTS industry VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE companies ADD COLUMN IF NOT EXISTS location VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS website VARCHAR(255);
ALTER TABLE companies ADD COLUMN IF NOT EXISTS size VARCHAR(20) DEFAULT 'SMALL';
